### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Perksey** [drogoganor/TextRender#1]

**Comment by drogoganor** [comment]
LGPL-3.0

https://github.com/OpenSAGE/OpenSAGE/blob/master/LICENSE.md

**Comment by Perksey** [comment]
Damn ok, thanks.

**Comment by drogoganor** [comment]
Yep it would have been MIT but used a component from OpenSAGE which is LGPL 3.0 I'm afraid.

**Comment by Perksey** [comment]
Which component? Perhaps it could be offloaded into a separate package (I’m
willing to PR to do so)

**Comment by Redhacker1** [comment]
#3 attempts to remedy the LGPL for this project (and SimpleGUI)
